name: FastAPI CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and tag Docker images using docker-compose
        run: |
          docker-compose up -d --build fastapi db ollama # Build all three services
          docker tag fastapi ${{ secrets.DOCKER_USERNAME }}/fastapi:${{ github.sha }}
          docker tag db ${{ secrets.DOCKER_USERNAME }}/db:${{ github.sha }}        # Tag db
          docker tag ollama ${{ secrets.DOCKER_USERNAME }}/ollama:${{ github.sha }}  # Tag ollama

      - name: Logging into Docker Hub
        run: docker login --username '${{ secrets.DOCKER_USERNAME }}' --password '${{ secrets.DOCKER_PASSWORD }}'

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/db:${{ github.sha }}          # Push db
          docker push ${{ secrets.DOCKER_USERNAME }}/ollama:${{ github.sha }}    # Push ollama