name: FastAPI CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, gpu]

    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        run: | 
          echo "${{ secrets.ENV_FILE_BASE64 }}" | base64 --decode > .env

      - name: Create Docker Network (if missing)
        run: docker network create chatbot_network || true
        
      - name: Build and tag Docker images using docker-compose
        run: |
          docker compose up -d --build
          docker ps -a
          docker tag fastapi ${{ secrets.DOCKER_USERNAME }}/fastapi:${{ github.sha }}
          docker tag db ${{ secrets.DOCKER_USERNAME }}/db:${{ github.sha }}        # Tag db
          docker tag ollama ${{ secrets.DOCKER_USERNAME }}/ollama:${{ github.sha }}  # Tag ollama

      - name: Logging into Docker Hub
        run: docker login --username '${{ secrets.DOCKER_USERNAME }}' --password '${{ secrets.DOCKER_PASSWORD }}'

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi:${{ github.sha }} # fastapi
          docker push ${{ secrets.DOCKER_USERNAME }}/db:${{ github.sha }}          # Push db
          docker push ${{ secrets.DOCKER_USERNAME }}/ollama:${{ github.sha }}    # Push ollama